full_data_path: TIGER-Lab/MathInstruct
model_name_or_path: microsoft/phi-2 # microsoft/Phi-3-mini-4k-instruct  # path to pretrained foundation llm
cache_dir: /home/chrisv/cache/
model_max_length: 512
schedule_name: Full
result_dir_name: preconfsam-0.05-mathinstruct_phi-2_3epochs_512-1gpu_lr2e-5_bs32
sam_mode: "preconfsam"
sam_rho: 0.05
sam_adaptive: false

train_args:
  gradient_checkpointing: TRUE
  optim: adamw_torch
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32
  eval_strategy: "epoch"
  save_strategy: "steps"
  save_steps: 250
  save_total_limit: 25
  learning_rate: 2.0e-5
  weight_decay: 0.
  warmup_ratio: 0.03
  lr_scheduler_type: cosine
  logging_steps: 1
  #fsdp: "full_shard auto_wrap" 
  #fsdp_config: 
  #  transformer_layer_cls_to_wrap: "torch.nn.TransformerDecoderLayer" # "Phi3DecoderLayer"
  bf16: TRUE
  tf32: TRUE
  group_by_length: TRUE
  full_determinism: TRUE
  seed: 42

#load_from: "preconfsam-0.05-pythia-70m-deduped-100-oneshot-130k_mathinstruct_phi-2_3epochs_900-singlegpu_lr5e-6propersave"


gradient_checkpointing: TRUE