full_data_path: TIGER-Lab/MathInstruct
model_name_or_path: microsoft/phi-2 # microsoft/Phi-3-mini-4k-instruct  # path to pretrained foundation llm
cache_dir: /data2/chris/data/huggingface_models
model_max_length: 900
schedule_name: Full
result_dir_name: fsam-0.10-pythia-70m-deduped-100-oneshot-130k_mathinstruct_phi-2_3epochs_900-singlegpu_lr5e-6propersave
sam_mode: "prefsam"
sam_rho: 0.1
sam_adaptive: false

train_args:
  optim: adamw_torch
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 16
  eval_strategy: "epoch"
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 25
  learning_rate: 5.0e-6
  weight_decay: 0.
  warmup_ratio: 0.03
  lr_scheduler_type: cosine
  logging_steps: 1
  #fsdp: "full_shard auto_wrap" 
  #fsdp_config: 
  #  transformer_layer_cls_to_wrap: "torch.nn.TransformerDecoderLayer" # "Phi3DecoderLayer"
  bf16: TRUE
  tf32: TRUE
  group_by_length: TRUE
  full_determinism: TRUE
  seed: 42

load_from: "fsam-0.10-pythia-70m-deduped-100-oneshot-130k_mathinstruct_phi-2_3epochs_900-singlegpu_lr5e-6propersave"